openapi: 3.0.0
info:
  title: FM Inventory
  description: FM Inventory
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Category
  - name: Vendor
paths:
  /api/category:
    post:
      tags:
        - Category
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Sub Title 2
                detail:
                  type: string
                  example: |-
                    alkdsjwjaldjald
                    adklwjalkjsdkljwakl
                inventory_forecast_id:
                  type: string
                  example: asldj01-=10i10123
                parent_id:
                  type: integer
                  example: '2'
                status:
                  type: string
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Category
      summary: index
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: status
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
        - name: sort_order
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/category/{category_id}:
    post:
      tags:
        - Category
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Title 1 Edited
                detail:
                  type: string
                  example: |-
                    alkdsjwjaldjald
                    adklwjalkjsdkljwakl
                inventory_forecast_id:
                  type: string
                  example: asdw
                parent_id:
                  type: integer
                  example: '1'
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: category_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Category
      summary: find by id
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: category_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/vendor:
    post:
      tags:
        - Vendor
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bishal Gurung
                phone:
                  type: string
                email:
                  type: string
                contact_persion:
                  type: string
                status:
                  type: string
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Vendor
      summary: index
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: status
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
        - name: sort_order
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/vendor/{vendor_id}:
    post:
      tags:
        - Vendor
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bishal Gurung
                phone:
                  type: integer
                  example: '989898'
                email:
                  type: string
                  example: grgbishal360@gmail.com
                contact_persion:
                  type: string
                  example: awalkjddkl
                status:
                  type: integer
                  example: '1'
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: vendor_id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Vendor
      summary: find by id
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: vendor_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
