openapi: 3.0.0
info:
  title: FM Inventory
  description: FM Inventory
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Category
  - name: Vendor
  - name: Coshh
  - name: Item
paths:
  /api/category:
    post:
      tags:
        - Category
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Sub Title 2
                detail:
                  type: string
                  example: |-
                    alkdsjwjaldjald
                    adklwjalkjsdkljwakl
                inventory_forecast_id:
                  type: string
                  example: asldj01-=10i10123
                parent_id:
                  type: integer
                  example: '1'
                status:
                  type: integer
                  example: '0'
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Category
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: status
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
          example: TITLE
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
        - name: paginate
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/category/{category_id}:
    post:
      tags:
        - Category
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Title 1 Edited
                detail:
                  type: string
                  example: |-
                    alkdsjwjaldjald
                    adklwjalkjsdkljwakl
                inventory_forecast_id:
                  type: string
                  example: asdws
                parent_id:
                  type: integer
                  example: '2'
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: category_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Category
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: category_id
          in: path
          schema:
            type: integer
          required: true
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/vendor:
    post:
      tags:
        - Vendor
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bishal Gurung
                phone:
                  type: integer
                  example: '1231'
                email:
                  type: string
                  example: asdw@gmai.com
                contact_persion:
                  type: integer
                  example: '1312'
                status:
                  type: integer
                  example: '0'
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Vendor
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: status
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
        - name: sort_order
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/vendor/{vendor_id}:
    post:
      tags:
        - Vendor
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bishal Gurung
                phone:
                  type: integer
                  example: '989898'
                email:
                  type: string
                  example: grgbishal360@gmail.com
                contact_persion:
                  type: string
                  example: awalkjddkl
                status:
                  type: integer
                  example: '1'
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: vendor_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Vendor
      summary: find by id
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: vendor_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/coshh:
    post:
      tags:
        - Coshh
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Coshh 2
                description:
                  type: string
                  example: |
                    alsdjlakjd
                    asjdlkwjdaklsjdklsajdwa
                image:
                  type: string
                  format: binary
                status:
                  type: string
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Coshh
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: status
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
          example: name
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/coshh/{coshh_id}:
    post:
      tags:
        - Coshh
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Coshh 1 edited
                description:
                  type: string
                  example: |
                    alsdjlakjd
                    asjdlkwjdaklsjdklsajdwa
                status:
                  type: integer
                  example: '0'
                _method:
                  type: string
                  example: PUT
                image:
                  type: string
                  format: binary
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: coshh_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Coshh
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: coshh_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/item:
    post:
      tags:
        - Item
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Coshh 1
                price:
                  type: integer
                  example: '123'
                description:
                  type: string
                  example: |
                    alsdjlakjd
                    asjdlkwjdaklsjdklsajdwa
                used_for:
                  type: string
                  example: adw
                category_id:
                  type: integer
                  example: '1'
                sub_category_id:
                  type: integer
                  example: '4'
                coshh_ids[]:
                  type: integer
                  example: '2'
                risk_assessments[abc]:
                  type: string
                  example: ab
                risk_assessments[b]:
                  type: string
                  example: bcde
                image:
                  type: string
                  format: binary
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Item
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: status
          in: query
          schema:
            type: integer
          example: '1'
        - name: paginate
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: sort_key
          in: query
          schema:
            type: string
          example: id
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
        - name: coshh_id
          in: query
          schema:
            type: string
        - name: category_id
          in: query
          schema:
            type: integer
          example: '2'
        - name: sub_category_id
          in: query
          schema:
            type: integer
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/item/{item_id}:
    post:
      tags:
        - Item
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Coshh 1 edited
                price:
                  type: integer
                  example: '123'
                description:
                  type: string
                  example: |
                    alsdjlakjd
                    asjdlkwjdaklsjdklsajdwa
                used_for:
                  type: string
                  example: adws
                category_id:
                  type: integer
                  example: '1'
                sub_category_id:
                  type: integer
                  example: '3'
                coshh_ids[]:
                  type: integer
                  example: '3'
                _method:
                  type: string
                  example: PUT
                status:
                  type: integer
                  example: '1'
                risk_assessments[abc]:
                  type: string
                  example: ab
                risk_assessments[b]:
                  type: string
                  example: bcde
                image:
                  type: string
                  format: binary
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: item_id
          in: path
          schema:
            type: integer
          required: true
          example: '8'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Item
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: item_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
